### ISSUE TITLE
Unable to install on Macbook M1

### ISSUE THREAD

**Issue by hugo53** [firebase/firebase-admin-python#530]
Hello there, 

I have an issue with `grpcio` when install firebase-admin via pip on my Macbook M1 (MacOS v11.0.1 (20B29)). Please check the log below for more details. Can you guys help me on this? Thanks in advance!

```
$ pip3 --version                                                                                                                    
pip 21.0.1 from /opt/homebrew/lib/python3.9/site-packages/pip (python 3.9)

$ pip3 install firebase-admin                                                                                 
Collecting firebase-admin
  Using cached firebase_admin-4.5.1-py3-none-any.whl (111 kB)
Collecting cachecontrol>=0.12.6
  Using cached CacheControl-0.12.6-py2.py3-none-any.whl (19 kB)
Collecting google-api-core[grpc]<2.0.0dev,>=1.14.0
  Using cached google_api_core-1.25.1-py2.py3-none-any.whl (92 kB)
Collecting google-cloud-storage>=1.18.0
  Using cached google_cloud_storage-1.35.0-py2.py3-none-any.whl (96 kB)
Collecting google-api-python-client>=1.7.8
  Using cached google_api_python_client-1.12.8-py2.py3-none-any.whl (61 kB)
Collecting google-cloud-firestore>=1.4.0
  Using cached google_cloud_firestore-2.0.2-py2.py3-none-any.whl (196 kB)
Collecting msgpack>=0.5.2
  Using cached msgpack-1.0.2.tar.gz (123 kB)
Collecting requests
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: setuptools>=40.3.0 in /opt/homebrew/lib/python3.9/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->firebase-admin) (51.1.1)
Collecting google-auth<2.0dev,>=1.21.1
  Using cached google_auth-1.24.0-py2.py3-none-any.whl (114 kB)
Requirement already satisfied: six>=1.13.0 in /opt/homebrew/lib/python3.9/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->firebase-admin) (1.15.0)
Collecting protobuf>=3.12.0
  Using cached protobuf-3.14.0-py2.py3-none-any.whl (173 kB)
Requirement already satisfied: pytz in /opt/homebrew/lib/python3.9/site-packages (from google-api-core[grpc]<2.0.0dev,>=1.14.0->firebase-admin) (2021.1)
Collecting googleapis-common-protos<2.0dev,>=1.6.0
  Using cached googleapis_common_protos-1.52.0-py2.py3-none-any.whl (100 kB)
Collecting grpcio<2.0dev,>=1.29.0
  Using cached grpcio-1.35.0.tar.gz (21.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /opt/homebrew/opt/python@3.9/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hd/9wzc30k576dccp88p__2rnn00000gn/T/pip-install-scc8wwdo/grpcio_b91b2b8a69b64b1b91e7951802a0f107/setup.py'"'"'; __file__='"'"'/private/var/folders/hd/9wzc30k576dccp88p__2rnn00000gn/T/pip-install-scc8wwdo/grpcio_b91b2b8a69b64b1b91e7951802a0f107/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/hd/9wzc30k576dccp88p__2rnn00000gn/T/pip-pip-egg-info-oqy4v1qk
         cwd: /private/var/folders/hd/9wzc30k576dccp88p__2rnn00000gn/T/pip-install-scc8wwdo/grpcio_b91b2b8a69b64b1b91e7951802a0f107/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hd/9wzc30k576dccp88p__2rnn00000gn/T/pip-install-scc8wwdo/grpcio_b91b2b8a69b64b1b91e7951802a0f107/setup.py", line 359, in <module>
        if mac_target and (pkg_resources.parse_version(mac_target) <
      File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 113, in parse_version
        return packaging.version.Version(v)
      File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
        match = self._regex.search(version)
    TypeError: expected string or bytes-like object
    ASM Builds for BoringSSL currently not supported on: macosx-11-arm64
    ----------------------------------------
```

**Comment by hiranya911** [comment]
Seems to be a known issue: https://github.com/googleapis/python-firestore/issues/285

Should really be addressed by the grpc team (they don't seem to be providing a distribution compatible with the Apple M1 right now).

**Comment by hugo53** [comment]
I resolved the problem by using `/usr/bin/python3` instead of `/opt/homebrew/bin/python3` (M1 native) with this command on Terminal (set Open with Rosetta).
```
arch -arch x86_64 /usr/bin/python3 -m pip install firebase-admin
```

**Comment by jrlindell** [comment]
> ```
> arch -arch x86_64 /usr/bin/python3 -m pip install firebase-admin
> ```

did this cause any problems with your ability to call it from an editor?

**Comment by hugo53** [comment]
> > ```
> > arch -arch x86_64 /usr/bin/python3 -m pip install firebase-admin
> > ```
> 
> did this cause any problems with your ability to call it from an editor?

I'm not sure much, only tried on Terminal Rosetta.

**Comment by finnatsea** [comment]
I am still having this problem, I'm not sure why the issue was closed. 

If you try to install firebase-admin on an Apple Silicon machine, python will try the setup wheel for grpico and fail. I'm on the m1 macbook air and I've tried it with python 3.8.2, 3.9.4, and 3.9.5. All the versions failed. I've tried it in a venv and globally, both failed.

Can someone explain what the above command does to fix the issue. It has not fixed it for me. Do I need to run all my programs that require firebase-admin using x86 python? If so, how is that done? Can I still use a venv?

My understanding so far is:
1. grpico is a dependency of firebase-admin, so `pip install firebase-admin` will try to install grpico
2. grpico is only compiled for x86, so upon trying the setup steps for grpico, something (pip maybe) starts running a bunch of `clang` commands, attempting to compile a version for arm
3. Some part of the compile fails and spits out a crazy looking error.

```
ERROR: Command errored out with exit status 1: /Users/brown/Developer/parse-tools/env/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] ...
```

My setup:
- Big Sur 11.4
- Python 3.9.5 (installed with homebrew) in a venv

**Comment by abe-winter** [comment]
the dependency here is firebase-admin -> google-storage -> resumable-media -> crc32c

fwiw I solved this in my codebase by forking firebase-admin, then removing the google-storage dependency in setup.py

firebase-admin can sort of survive without google-storage, depending on exactly which features you need

if you need google-storage functionality, another option might be to fork the resumable-media package and use builtin `zlib.crc32` instead of crc32c, but that's more complex.

**Comment by diaconori** [comment]
> I resolved the problem by using `/usr/bin/python3` instead of `/opt/homebrew/bin/python3` (M1 native) with this command on Terminal (set Open with Rosetta).
> 
> ```
> arch -arch x86_64 /usr/bin/python3 -m pip install firebase-admin
> ```

thank you so much, i've been stuck at this for hours, not being able to find any possible solutions.

**Comment by mirorac** [comment]
This [answer on stackoverflow](https://stackoverflow.com/a/68185347/1353874) worked for me
